export const webConstants = {
  API: {
    LOGIN_USER: "/user/loginUser",
    USER_LIST: "/user/userList",
    CHAT_LIST: "/chat/chatList",
    CHAT_ROOM: "/room/chatRoom",
    CREATE_CHAT_ROOM: "/room/createRoom",
    UPDATE_CHAT_ROOM: "/room/updateRoom",
    LAST_SEEN: "/room/lastSeen",
    CREATE_USER_STATUS: "/status/createStatus",
    GET_ALL_STATUS: "/status/getAllStatus",
    SET_STATUS_VIEWED: "/status/statusViewed"
  },
  WEB_TIMER_UUID: "WEB_TIMER_UUID",
  USER_ID: "UserId",
  PATIENT_NAME: "PATIENT_NAME",
  ACCESS_TOKEN: "AccessToken",
  USER_NAME: "UserName",
  TIME_FORMAT: "hh:mm A",
  DATE_TIME_FORMAT: "DD MMM YYYY hh:mm A",
  FRIEND: "FRIEND",
  OWNER: "OWNER",
  CHAT_ROOM: "CHAT_ROOM",
  CHAT_LIST: "CHAT_LIST",
  CHAT_VIEWED: "CHAT_VIEWED",
  USER_STATUS: "USER_STATUS",
  LAST_SEEN: "LAST_SEEN",
  REGISTER_TIMER: "REGISTER_TIMER",
  REGISTER_TIMER_RESP: "REGISTER_TIMER_RESP",
  SCAN_QR_CODE_CONFIRM: "SCAN_QR_CODE_CONFIRM",
  START_WEB_TIMER: "START_WEB_TIMER",
  PAUSE_WEB_TIMER: "PAUSE_WEB_TIMER",
  PAPER_ELEVATION: 5,
  STATUS_MARGIN: "4%",
  STATUS_IMAGE_SIZE: 45
};
